### ISSUE TITLE
Getting Request Denied

### ISSUE THREAD

**Issue by firdausalif** [akexorcist/Android-GoogleDirectionLibrary#34]
Hello, im always get Reques_Denied, i've enable direction API, what should i do?

**Comment by sagar-bhatt** [comment]
I suggest checking few things before we dig deeper:

1. Check you are not using expired key / a key associated with the wrong project
2. Use Server Key, instead of Android key
3. Make sure you have enabled Directions API from the API console
4. Make sure you are not supplying any wrong parameters i.e. from, to locations.

At last, try some static example from author's [documentation guide](http://www.akexorcist.com/2015/12/google-direction-library-for-android-en.html) - usage examples! 
Please let us know how it goes!

Best,
Sagar

**Comment by firdausalif** [comment]
Oh i see get error when converting LatLng to latitude/longitude,  
java.lang.NumberFormatException: Invalid double: "lat/lng: (-6.192474" , the value have "(". Any idea bro?
